name: FriendCraft
version: "${project.version}"
main: com.nixielabs.friendcraft.FriendCraft
commands:
  fc:
    description: The primary command interface to FriendCraft
    usage: '§eAvailable commands: §fadd <player>§e, §fremove <player>§e, §flist§e, §fshow§e, §fhide§e. See §f/fc help <command>§e for details.'
    permission: friendcraft.fc
    permission-message: '§eYou don''t have permission to manage your friends list.'
  msg:
    description: Send a message to another player via FriendCraft
    usage: '§eUsage: §f/msg <player> <message>'
    permission: friendcraft.msg
    permission-message: '§eYou don''t have permission to message other players.'
  r:
    description: Send a reply to the last person who messaged you
    usage: '§eUsage: §f/r <message>'
    permission: friendcraft.msg
    permission-message: '§eYou don''t have permission to message other players.'
depend: []
softdepend: []
database: false
website: "https://nixielabs.com/friendcraft"
description: ""
author: "Tom Heinan"
authors:
  - "Tom Heinan"
load: postworld
#permissions:
